#!/usr/bin/env bash
# A Bash script that displays all running processes in the required format with seconds

ps -eo user,lstart,command --forest | awk '
NR==1 {
  printf "%-8s %-20s %s\n", "USER", "STARTED", "COMMAND"
  next
}
{
  printf "%-8s %s %s\n", $1, $2" "$3" "$4" "$5" "$6, substr($0, index($0,$8))
}'
