#!/usr/bin/env bash
# Display numbers 1 to 20; print special bad luck messages for 4, 9, and 17 using a case statement

count=1
while [ $count -le 20 ]; do
  echo "$count"
  case $count in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  ((count++))
done
